server:
  port: 9002
  
spring:
  application:
    name: USER-SERVICE  
  zipkin:
    base-url: 127.0.0.1:9411/
eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http:/localhot:8761/eureka/
  inatance:
    hostname: localhost